name: Keep Supabase Alive

on:
  schedule:
    # Runs at 00:00 UTC every day to ensure it stays active
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to manually trigger it from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        run: |
          curl -f -X GET "https://taprukpiubqsckahocaz.supabase.co/rest/v1/nclex_data?select=key&limit=1" \
            -H "apikey: sb_publishable_V1u7recZMcdc2-DXhoMwoQ_BEVWej3g" \
            -H "Authorization: Bearer sb_publishable_V1u7recZMcdc2-DXhoMwoQ_BEVWej3g"
